### ISSUE TITLE
Unable to decode lte rrc UE-EUTRA-Capability message

### ISSUE THREAD

**Issue by ghost** [mouse07410/asn1c#120]
Hi
UE-EUTRA-Capability PDU is not decoded when the message length is large.

`./rrc-dump -iuper  -p UE-EUTRA-Capability UE_EUTRA_Capability_0.uper`

error:
`UE_EUTRA_Capability_0.uper: Decode failed past byte 0: Input processing error`

[UE_EUTRA_Capability_0.zip](https://github.com/mouse07410/asn1c/files/10934943/UE_EUTRA_Capability_0.zip)

`3GPP TS 36.331 V17.1.0 (2022-06)`

**Comment by mouse07410** [comment]
Sorry, no idea. But the location of the failure seems to suggest that message size does not play a role here?

**Comment by mouse07410** [comment]
No idea how to proceed, closing.
