### ISSUE TITLE
Consider adding AUTOMATIC TAGS after module NR-RRC-Definitions DEFINITIONS, or manually tag components in NR-RRC-Definitions.asn

### ISSUE THREAD

**Issue by samrajput1143** [mouse07410/asn1c#122]
Iam using 3gpp RRC rel 17 asn file.
[https://obj-sys.com/products/asn1apis/lte_nr_rrc_rel17_c_lnx.tar.gz](url)

[asn.zip](https://github.com/mouse07410/asn1c/files/11136626/asn.zip)

**Comment by samrajput1143** [comment]
asn1c -pdu=auto -fincludes-quoted -fcompound-names -fno-include-deps -no-gen-OER -no-gen-example *.asn

**Comment by mouse07410** [comment]
I don't understand - what is the problem (what and where is the bug), and what's the proposed fix? In the form of Pull Request, preferably?

**Comment by mouse07410** [comment]
Apparently, no actions to take.
