### ISSUE TITLE
Decode base64 UPER encoded string

### ISSUE THREAD

**Issue by MartijnHarmenzon** [mouse07410/asn1c#124]
Hello all. Can anyone please help me out on how to decode the following base64 string using asn1c?
It is a SPATEM message and I assume it is UPER encoded.
Thanks so much in advance.

AQR7NgAKIRkuZLmAHA0tg0ZtlrG9mwAFgAIACHAB5JBkBYMgEENUZQxlCKAsGYECGqMoYyhFAWDUDBDVGUMZQigLBuCAhqjKGMoRQFg4BQQ1RlDGUIoCyagwIaoyhjKEUBZNgcENUZQxlCI=

**Comment by mouse07410** [comment]
No clue. In fact, I've no clue what SPATEM is, and don't have time to dig around looking for it.

In general, to seek help I'd recommend providing:
- a **simple** ASN.1 definition that includes the problematic component;
- an XML-encoded value that should be encoded or decoded;
- the actual encoding (say, in HEX) that fails to decode, or was encoded incorrectly;
- any compiler or codec errors in the process.

Given only what you provided - sorry, but I cannot help.
