### ISSUE TITLE
Using fuzzing with asn1c

### ISSUE THREAD

**Issue by Brunty360** [mouse07410/asn1c#180]
Is there any documentation on the use of fuzzing with the asn1c compiler? I can see issues have bene raised against fuzzing but I can't find any information on its usage

**Comment by mouse07410** [comment]
It would make sense to fuzz the code **generated** by the `asn1c` compiler. It doesn't make a lot of sense to fuzz the compiler itself. 

On the other hand, the documentation is in your fuzzer tool, whichever one you use. 

Fuzz and report - if the findings turn out easy to fix, or (less likely) of importance - we'll do our best to take care of them.
