### ISSUE TITLE
Typedef error and not included code

### ISSUE THREAD

**Issue by KIN92** [mouse07410/asn1c#190]
Hello, I was working on the H323 decoder, some errors occurred while working, they have all been resolved, but I think you should take a look.

OCTET_STRING_aper.c contains commented out code that causes the parser to crash on certain messages. When turned on it works correctly. I would like to know why it is commented out and whether its inclusion in any cases can lead to incorrect behavior?

There is also incorrect nesting of structures, which leads to errors on all compilers.
I will attach an archive with a brief visual description.
Thank you!

https://transfiles.ru/ov6ij

**Comment by mouse07410** [comment]
> OCTET_STRING_aper.c contains commented out code that causes the parser to crash on certain messages

Would you mind being more specific? I assume it's about https://github.com/mouse07410/asn1c/blob/940dd5fa9f3917913fd487b13dfddfacd0ded06e/skeletons/OCTET_STRING_aper.c#L75 ? Or did you uncomment something else?

**Comment by KIN92** [comment]
That's right, just this piece of code, nothing else

**Comment by mouse07410** [comment]
Thank you - uncommented in the current default (`vlm_master`).

**Comment by shuimoshusheng** [comment]
@KIN92 Could you please print out the `cval->range_bits` value? Is it a multiple of 8?

**Comment by mouse07410** [comment]
OK, @KIN92 don't bother. I found the problem in your patch, reverted it, and re-implemented according to the standard. Final correction went in today. 

@shuimoshusheng please confirm that the **current** `vlm_master` works correctly for you.

@v0-e please take a look, if you can.

**Comment by shuimoshusheng** [comment]
> OK, @KIN92 don't bother. I found the problem in your patch, reverted it, and re-implemented according to the standard. Final correction went in today.
> 
> @shuimoshusheng please confirm that the **current** `vlm_master` works correctly for you.
> 
> @v0-e please take a look, if you can.

I tested the current version `vlm_master` and found that the PrintableString type is properly encoded and decoded. Thank you!!!
