### ISSUE TITLE
RRC code generation error

### ISSUE THREAD

**Issue by shuimoshusheng** [mouse07410/asn1c#197]
code version：commit 18e565032e52af8002c2353be20bdbba9233e700 (HEAD -> vlm_master, origin/vlm_master, origin/HEAD)
asn file [wireshark-asn1-nr-rrc](https://github.com/wireshark/wireshark/tree/master/epan/dissectors/asn1/nr-rrc)

command:  `asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D asn1/nr-rrc/*asn `
```c
// RRC_CA-BandwidthClassNR-r17.h
/* Dependencies */
typedef enum RRC_CA_BandwidthClassNR_r17 {
	RRC_CA_BandwidthClassNR_r17_r	= 0,
	RRC_CA_BandwidthClassNR_r17_s	= 1,
	RRC_CA_BandwidthClassNR_r17_t	= 2,
	RRC_CA_BandwidthClassNR_r17_u	= 3
	/*
	 * Enumeration is extensible
	 */
} e_RRC_CA_BandwidthClassNR_r17;

/* RRC_CA-BandwidthClassNR-r17 */
typedef long	 RRC_CA_BandwidthClassNR_r17_t;
```
There are duplicate identifiers in the C code. 

Should the code `typedef long  RRC_CA_BandwidthClassNR_r17_t;`  to be `typedef long RRC_CA_BandwidthClassDL_NR_r17_t;` or  `typedef long RRC_CA_BandwidthClassUL_NR_r17_t;` or DL and UL are unified as  `typedef long  RRC_CA_BandwidthClass_NR_r17_t;`  ?

Definition of ASN file：
```asn

CA-BandwidthClassNR-r17 ::=         ENUMERATED {r, s, t, u, ...}

BandParameters-v1770 ::=         SEQUENCE {
    ca-BandwidthClassDL-NR-r17       CA-BandwidthClassNR-r17                    OPTIONAL,
    ca-BandwidthClassUL-NR-r17       CA-BandwidthClassNR-r17                    OPTIONAL
}

BandParameters-v1780 ::=         SEQUENCE {
    ca-BandwidthClassDL-NR-r17       CA-BandwidthClassNR-r17                    OPTIONAL,
    ca-BandwidthClassUL-NR-r17       CA-BandwidthClassNR-r17                    OPTIONAL,
    supportedAggBW-FR2-r17           SEQUENCE {
        supportedAggBW-DL-r17            SupportedAggBandwidth-r17               OPTIONAL,
        supportedAggBW-UL-r17            SupportedAggBandwidth-r17               OPTIONAL
    }    OPTIONAL
}
```

**Comment by mouse07410** [comment]
Thank you for reporting. Offhand, I've no clue how to approach this problem, short of suggesting that you manually edit the generated .h file.

Perhaps, one of the `asn1c` many flags would help here?

**Comment by shuimoshusheng** [comment]
> Thank you for reporting. Offhand, I've no clue how to approach this problem, short of suggesting that you manually edit the generated .h file.
> 
> Perhaps, one of the `asn1c` many flags would help here?

Okay, it has been manually changed. Thank you！
