### ISSUE TITLE
Can we rename HAVE_CONFIG_H?

### ISSUE THREAD

**Issue by mtfurlan** [mouse07410/asn1c#201]
`HAVE_CONFIG_H` is also defined by [CppUTest](https://github.com/cpputest/cpputest), and trying to use it with asn1c generated code is causing slight annoyance

Can we rename `HAVE_CONFIG_H` to `ASN1C_HAVE_CONFIG_H`?

I'm not super sure what `HAVE_CONFIG_H` is supposed to be for, it's not mentioned in any documentation

**Comment by mouse07410** [comment]
I'd prefer `HAVE_ASN1C_CONFIG_H`

**Comment by mtfurlan** [comment]
Sounds good, would you like me to make a PR?

**Comment by mouse07410** [comment]
Yes please.

**Comment by mtfurlan** [comment]
pretty sure it's impossible, see pr for details
