### ISSUE TITLE
Compiling with J2735

### ISSUE THREAD

**Issue by tonychen091** [mouse07410/asn1c#21]
Just wanted to hear a little more about the work you did to get your fork work for J2735. We're doing the same and would love to pick your brain.

**Comment by mouse07410** [comment]
I'm not the one who did the bulk of work on this addition. @brchiu is the one you want to talk to.

But if my fork works for you with J2735 - why is that not sufficient? ;-)

**Comment by mouse07410** [comment]
If you'd like to ask something specific - please feel free to do so.

Otherwise, I'll give this issue a few days and close it, as it appears that there's nothing that needs to be done with this fork.

**Comment by mouse07410** [comment]
OK, as there seem to be no specific questions posted that I (or @brchiu) could answer here - I'm closing this issue. Please feel free to re-open otherwise.
