### ISSUE TITLE
auto-gen Code fails to parse some S1AP IEs (PLMNIdentity) 

### ISSUE THREAD

**Issue by jeick2008** [mouse07410/asn1c#24]
Hello ,guys,
       Thank you for your working. I got a problem that asn1c generated code with(ASN:  https://github.com/ikarso/3GPPTS36.413_AuthenticEshkinKot). But it can't parse any IEs which contains PLMNIdentity. 

the attachment is my test packet.
If possible,  pls check it . Thank you very much.
[AttachReq.zip](https://github.com/mouse07410/asn1c/files/1009492/AttachReq.zip)

**Comment by brchiu** [comment]
@jeick2008,

@ikarso's sample code does not handle ProtocolIE-Field with `id-NAS-PDU (value 26)`, you need to add it on your own. Below is my test result using the S1AP-PDU inside your pcap file after add NAS-PDU  handler. 

Moreover, if you want to process the content inside each fields, for example to parse `plmn identity`, `mcc`, `mnc` and `tac` in `00 64 F0 00 78 1C` of `id-TAI (value 67)`, you also need write corresponding code to decode them by yourself.

You are encouraged to improve `asn1c` to add capability of decoding inner content of each field. 
It will be greatly appreciated.

```
./s1ap-dump ./sample-S1AP-InitialUEMessage2.aper 
InitiatingMessage ::= {
    procedureCode: 12
    criticality: 1
    value: 
        00 00 05 00 08 00 04 80 15 00 E1 00 1A 00 6C 6B 
        17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 80 
        5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 D0 
        31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 00 
        00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 00 
        52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 03 
        57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C A0 
        40 08 04 02 60 04 00 02 1F 02 E0 00 43 00 06 00 
        64 F0 00 78 1C 00 64 40 08 00 64 F0 00 78 5E 20 
        C0 00 86 40 01 30
}
procedureCode: 12
criticality: 1
size: 150
DownlinkNASTransport ::= {
    protocolIEs: ProtocolIE-Container ::= {
        ProtocolIE-Field ::= {
            id: 8
            criticality: 0
            value: 80 15 00 E1
        }
        ProtocolIE-Field ::= {
            id: 26
            criticality: 0
            value: 
                6B 17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 
                80 5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 
                D0 31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 
                00 00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 
                00 52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 
                03 57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C 
                A0 40 08 04 02 60 04 00 02 1F 02 E0
        }
        ProtocolIE-Field ::= {
            id: 67
            criticality: 0
            value: 00 64 F0 00 78 1C
        }
        ProtocolIE-Field ::= {
            id: 100
            criticality: 1
            value: 00 64 F0 00 78 5E 20 C0
        }
        ProtocolIE-Field ::= {
            id: 134
            criticality: 1
            value: 30
        }
    }
}

Field 0:
id 8
criticality 0
id_eNB_UE = 1376481

Field 1:
id 26
criticality 0

    17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 80 
    5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 D0 
    31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 00 
    00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 00 
    52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 03 
    57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C A0 
    40 08 04 02 60 04 00 02 1F 02 E0

Field 2:
id 67
criticality 0

Field 3:
id 100
criticality 1

Field 4:
id 134
criticality 1
establishment_cause = 3
```

**Comment by jeick2008** [comment]
@brchiu Yes, thank you . What I said was not in @ikarso's sample code. But my test code. 
Code likes:

// 3GPP 36.413 9.2.3.16
static void processTAI(ANY_t * value)
{    
    TAI_t *tai  = NULL;
    uint8_t TAC[4];
    if (!ANY_to_type_aper(value, &asn_DEF_TAI, (void **)&tai))
    {
        memcpy(TAC, tai->tAC.buf,
                            get_lower_one(sizeof(TAC), tai->tAC.size)); 
        DPI_LOG_DEBUG("[LCORE: %u] TAI(TAC) = %hx\n", self_lcore_id, g_xdr_info->TAC);
    }
}

ANY_to_type_aper returns -1, and aper_decode returns rval.code== RC_WMORE

**Comment by jeick2008** [comment]
@brchiu , in 3GPP 36.413 ProtocolIE- id (67) is TAI. As spec, TAI contains PLMNIdentity and tAC.
Below is my test result, it is same with yours. Moreover, tAC is not parsed out.  
InitialUEMessage ::= {
    protocolIEs: ProtocolIE-Container ::= {
        ProtocolIE-Field ::= {
            id: 8
            criticality: 0
            value: 80 15 00 E1
        }
        ProtocolIE-Field ::= {
            id: 26
            criticality: 0
            value: 
                6B 17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 
                80 5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 
                D0 31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 
                00 00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 
                00 52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 
                03 57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C 
                A0 40 08 04 02 60 04 00 02 1F 02 E0
        }
        ProtocolIE-Field ::= {
            id: 67
            criticality: 0
            value: 00 64 F0 00 78 1C
        }
        ProtocolIE-Field ::= {
            id: 100
            criticality: 1
            value: 00 64 F0 00 78 5E 20 C0
        }
        ProtocolIE-Field ::= {
            id: 134
            criticality: 1
            value: 30
        }
    }
}
DPI-[DEBUG]: [LCORE: 0] Item 0: id-eNB-UE-S1AP-ID
DPI-[DEBUG]: [LCORE: 0] id: id-eNB-UE-S1AP-ID (8)
DPI-[DEBUG]: [LCORE: 0] criticality 0
DPI-[DEBUG]: [LCORE: 0] id_eNB_UE = 1376481
DPI-[DEBUG]: [LCORE: 0] ------------------------------------
DPI-[DEBUG]: [LCORE: 0] Item 1: id-NAS-PDU
DPI-[DEBUG]: [LCORE: 0] id: id-NAS-PDU (26)
DPI-[DEBUG]: [LCORE: 0] criticality 0
DPI-[DEBUG]: [LCORE: 0] ------------------------------------
DPI-[DEBUG]: [LCORE: 0] Item 2: id-TAI
DPI-[DEBUG]: [LCORE: 0] id: id-TAI (67)
DPI-[DEBUG]: [LCORE: 0] criticality 0
DPI-[DEBUG]: [LCORE: 0] ------------------------------------
DPI-[DEBUG]: [LCORE: 0] Item 3: id-EUTRAN-CGI
DPI-[DEBUG]: [LCORE: 0] id: id-EUTRAN-CGI (100)
DPI-[DEBUG]: [LCORE: 0] criticality 1
DPI-[DEBUG]: [LCORE: 0] ------------------------------------
DPI-[DEBUG]: [LCORE: 0] Item 4: id-RRC-Establishment-Cause
DPI-[DEBUG]: [LCORE: 0] id: id-RRC-Establishment-Cause (134)
DPI-[DEBUG]: [LCORE: 0] criticality 1
DPI-[DEBUG]: [LCORE: 0] establishment_cause = 3

**Comment by brchiu** [comment]
hi, @jeick2008, 

Yes, you are right ! 
There is indeed one problem in `asn1c` that `asn_DEF_PLMNidentity` should inherit `per_constraints` from `asn_DEF_TBCD_STRING`. My [pull request](https://github.com/vlm/asn1c/pull/93) did not handle this well. I will try to find a fix to it. Please stay tuned !

**Comment by brchiu** [comment]
hi, @jeick2008 ,

I prepare a fix to issue 24 at [this branch](https://github.com/brchiu/asn1c/tree/mouse_master_fix_issue_24)
It is based on mouse07410's master branch. 
If you have time, please have some tests. 
I will send pull request to mouse07410 later on.

Below is decoding result of your sample message : 
```
InitiatingMessage ::= {
    procedureCode: 12
    criticality: 1
    value: 
        00 00 05 00 08 00 04 80 15 00 E1 00 1A 00 6C 6B 
        17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 80 
        5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 D0 
        31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 00 
        00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 00 
        52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 03 
        57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C A0 
        40 08 04 02 60 04 00 02 1F 02 E0 00 43 00 06 00 
        64 F0 00 78 1C 00 64 40 08 00 64 F0 00 78 5E 20 
        C0 00 86 40 01 30
}
procedureCode: 12
criticality: 1
size: 150
InitialUEMessage ::= {
    protocolIEs: ProtocolIE-Container ::= {
        ProtocolIE-Field ::= {
            id: 8
            criticality: 0
            value: 80 15 00 E1
        }
        ProtocolIE-Field ::= {
            id: 26
            criticality: 0
            value: 
                6B 17 FF 5A B6 93 12 07 41 11 0B F6 64 F0 00 83 
                80 5C C0 23 96 B1 05 F0 70 00 40 11 00 23 02 07 
                D0 31 27 1D 80 80 21 10 01 00 00 10 81 06 00 00 
                00 00 83 06 00 00 00 00 00 0D 00 00 03 00 00 0A 
                00 52 64 F0 00 78 1C 5C 0A 00 31 03 E5 E0 3E 11 
                03 57 58 A6 20 0B 60 14 04 EF 65 22 06 1E 24 1C 
                A0 40 08 04 02 60 04 00 02 1F 02 E0
        }
        ProtocolIE-Field ::= {
            id: 67
            criticality: 0
            value: 00 64 F0 00 78 1C
        }
        ProtocolIE-Field ::= {
            id: 100
            criticality: 1
            value: 00 64 F0 00 78 5E 20 C0
        }
        ProtocolIE-Field ::= {
            id: 134
            criticality: 1
            value: 30
        }
    }
}

Field 0:
id 8
criticality 0
id_eNB_UE = 1376481

Field 1:
id 26
criticality 0

Field 2:
id 67
criticality 0
TAI ::= {
    pLMNidentity: 64 F0 00
    tAC: 78 1C
}

Field 3:
id 100
criticality 1
EUTRAN-CGI ::= {
    pLMNidentity: 64 F0 00
    cell-ID: 78 5E 20 C0
}

Field 4:
id 134
criticality 1
establishment_cause = 3
```

**Comment by mouse07410** [comment]
@brchiu I'm ready to receive and review changes/PR. ;-)

**Comment by brchiu** [comment]
@mouse07410,  Don't forget that we are in different timezone. That was almost 2:00 am at Taipei. :)

**Comment by jeick2008** [comment]
@brchiu  thank you for your hard working.  It works well after patch your changeset.

**Comment by mouse07410** [comment]
Thanks to @brchiu this problem has been fixed, so the issue is closed.
