### ISSUE TITLE
Build Failure due to missing asn1p_l.c

### ISSUE THREAD

**Issue by usman092** [mouse07410/asn1c#28]
I am trying to build the compiler but make gives the following error,

> make[3]:
> Entering directory '/home/ubx/usha_workspace/git/asn1c/libasn1parser'
>  LEX      asn1p_l.c
>%option yylineno entails a performance penalty ONLY on rules that can match newline characters
>REJECT entails a large performance penalty
>lex.yyasn1p_l.c is unchanged
>  CC       asn1p_l.lo
>gcc: error: asn1p_l.c: No such file or directory
>gcc: fatal error: no input files
>compilation terminated.

@mouse07410  Kindly check if the build is successful locally on your system.

**Comment by velichkov** [comment]
Hi @usman092 

Check that you have `flex` and `bison` installed. If you have them but it still fails provide the `config.log` and the full output of `make V=1`

We are using Travis CI and [here](https://travis-ci.org/mouse07410/asn1c) you could see that it builds successfully on both OSX and Ubuntu Precise

**Comment by usman092** [comment]
I had installed flex and bison but it was not solving the issue. Getting a new repository fixed it
