### ISSUE TITLE
it is fail to compile the generated code 

### ISSUE THREAD

**Issue by jeick2008** [mouse07410/asn1c#35]
Hello, @mouse07410 
         I generate the codes within the latest version in this repo , the data files are under wireshare(dissectors/asn1/s1ap). But I get many errors when compiling the codes, just like bellow:
                 ```
from ../src/HandoverRequired.c:8:
../include/ProtocolIE-SingleContainer.h:21:1: error: unknown type name ‘Bearers_SubjectToStatusTransfer_ItemIEs_t’
 typedef Bearers_SubjectToStatusTransfer_ItemIEs_t  ProtocolIE_SingleContainer_127P0_t;
 ^
../include/ProtocolIE-SingleContainer.h:22:1: error: unknown type name ‘E_RABInformationListIEs_t’
 typedef E_RABInformationListIEs_t  ProtocolIE_SingleContainer_127P1_t;
 ^
../include/ProtocolIE-SingleContainer.h:23:1: error: unknown type name ‘E_RABItemIEs_t’
 typedef E_RABItemIEs_t  ProtocolIE_SingleContainer_127P2_t;
 ^
../include/ProtocolIE-SingleContainer.h:24:1: error: unknown type name ‘MDTMode_ExtensionIE_t’
 typedef MDTMode_ExtensionIE_t  ProtocolIE_SingleContainer_127P3_t;

^
../include/ProtocolIE-SingleContainer.h:25:1: error: unknown type name ‘RecommendedCellItemIEs_t’
 typedef RecommendedCellItemIEs_t  ProtocolIE_SingleContainer_127P4_t;
 ^
../include/ProtocolIE-SingleContainer.h:26:1: error: unknown type name ‘RecommendedENBItemIEs_t’
 typedef RecommendedENBItemIEs_t  ProtocolIE_SingleContainer_127P5_t;
```
```
I move the header files to incldue, source files to src, the Makefile is working under dir build. the file path:
gencode----build
              |
             ----include
              |
             ----src

Can you help me how to fix it. Thank you so much.

**Comment by mouse07410** [comment]
I wonder how you generated the files from ASN.1 - what parameters you passed to `asn1c`. Perhaps you missed adding `-pdu=all` and `-fcompound_names`?

I cannot tell any more until I see the complete `asn1c` and compiler invocation.

**Comment by jeick2008** [comment]
Hello，@mouse07410,
          Sorry, so long time to reply U. I get a operating log for generating the code via AN1C with asn data. The data files are from wireshark(wireshark-master\epan\dissectors\asn1\s1ap).
        The details are in the attachment .  Thanks so much for your working.
[asn1c_mouse07410_compiled_error_s1ap.log](https://github.com/mouse07410/asn1c/files/2296384/asn1c_mouse07410_compiled_error_s1ap.log)

**Comment by brchiu** [comment]
@jeick2008, 

Add -indirect-choice when you generate C files with asn1c. If asn1c does not recognize this command line option, try asn1c -h to find one with similar name.

This error comes from cyclic header file inclusion, -indirect-choice is currently only available solution to it.

**Comment by jeick2008** [comment]
@brchiu
    Thank you so much, I try it right now.

**Comment by jeick2008** [comment]
@brchiu 
  The command likes "asn1c -fcompound-names -findirect-choice -gen-PER -pdu=all ../../data/S1AP-*", but the codes are still failed to compile.
The Error info is same.

**Comment by brchiu** [comment]
@jeick2008,

Have a look at https://github.com/brchiu/asn1c/blob/velichkov_s1ap_plus_option_group/examples/sample.source.S1AP/Makefile
, perhaps adding -pdu=all -fcompound-names -findirect-choice -fno-include-deps can help.

**Comment by brchiu** [comment]
By the way, coalesce all S1AP modules into one file instead of keeping them as separate ones might be another key point.

**Comment by jeick2008** [comment]
@brchiu 
After adding -fno-include-deps , The issue about cyclic header file inclusion, but some functions redefined in ProtocolIE-Feilds.c, such as memb_id_constraint_0,memb_criticality_constraint_0, etc...
May be I should keep the files all in one instead of separate ones. I will try it.

**Comment by jeick2008** [comment]
@brchiu 
Brchiu, Even though I keep the asn files all in one, many structs redefined are still there. And all errors are occurred in ProtocolIE-Field.c

**Comment by brchiu** [comment]
@jeick2008 , perhaps you can use this branch of my repository https://github.com/brchiu/asn1c/tree/velichkov_s1ap_plus_option_group

**Comment by brchiu** [comment]
@jeick2008, strangely, even using this repository, I can compile the generated C files.
Have you re-generated C file again with `make regen-makefile` ?

**Comment by mouse07410** [comment]
@brchiu, thanks for your help!

@jeick2008 can you please confirm that after doing `make regen-makefile` your error disappears?

**Comment by jeick2008** [comment]
@mouse07410 I did not use the makefile in example, I just copied the cmd line  to my makefile. The compilation issue still exists. 
It may be caused by the data file. Though, Thank you and @brchiu  for your hard working. 
pls close the issue.
