### ISSUE TITLE
SET_OF encoding

### ISSUE THREAD

**Issue by OYTIS** [mouse07410/asn1c#37]
I'm getting a segfault when encoding data containing "SET OF"s. In the [code](https://github.com/mouse07410/asn1c/blob/vlm_master/skeletons/constr_SET_OF.c#L1296) there is a zero in place of encoding function for SET_OF.

Is it just not yet implemented, or is it intended and my problem is somewhere else?

Thanks!

**Comment by velichkov** [comment]
Hi @OYTIS,

> Is it just not yet implemented

Yes, it seems so. You could use `SET_OF_encode_uper` as a base for an implementation.

**Comment by mouse07410** [comment]
@OYTIS looking forward to see your PR updated

**Comment by mouse07410** [comment]
Closing this issue. @OYTIS, please create a new PR when you're ready to submit the tests.
