### ISSUE TITLE
make check fails for 32bit crossdev environment

### ISSUE THREAD

**Issue by dfranusic** [mouse07410/asn1c#46]
I am using `crossdev` enviroment to compile for `32bit armv7a SoC board` on my `64bit Intel i5` Gentoo Linux system. As you are probably aware, compiling directly on arm boards is notoriously slow and this is the preferred way. 

Although asn1c works great for my needs (I  have tested the compiler and decoder in DER mode and everything works fine) and I don't need PER support, it seems that some of the tests concerning PER are buggy. I have tested this with `qemu_binfmt` environment and also on the real board with `Marvell ARMADA A388 ARM A9`. The problem seems to be related to tests using `readdir` and other filesystem functions when run on a 64bit host. 

```bash
$ ./configure --disable-test-asan --disable-test-ubsan --host=armv7a-hardfloat-linux-gnueabi
$ make -j4
$ make check
```

Tests that fail are some from the `tests/tests-c-compiler` directory, the ones reading from the filesystem:
- test-check-119.-fwide-types.-gen-PER
- test-check-119.-gen-PER
- test-check-126.-gen-PER
- test-check-62
- test-check-70
- test-check-70.-fwide-types

I have made the necessary changes and will create a pull request. The changes in the pull request deal with all these issues and will allow asn1c to be compatible with `crossdev` environments and also with `qemu_binfmt`

The same process works without issues when target host is unchanged (64bit -> 64bit)
```bash
$ ./configure --disable-test-asan --disable-test-ubsan
$ make -j4
$ make check
```
All tests are successful.

**Comment by mouse07410** [comment]
Thank you! Let me review your PR with @velichkov, and merge.
