### ISSUE TITLE
the codes generated by asn1c compiled error(S1AP)

### ISSUE THREAD

**Issue by jeick2008** [mouse07410/asn1c#48]
@mouse07410 At first, thank you for your hard working, this issue I ever asked. Now I just want to decode the S1AP signalling (3GPP R15 36.413). 
1. I cloned the code from:  https://github.com/mouse07410/asn1c.git    vlm_master
2. compile the project;(make, make install)
3. put the asn data files into one asn file, then put it under dir  example( [s1ap-14.4.0.zip](https://github.com/mouse07410/asn1c/files/3058791/s1ap-14.4.0.zip))
4. under example/sample.source.S1AP : make regen-makefile
5. after step 4, execute make 
lots of errors like below:
```
make
cc -DHAVE_CONFIG_H -DJUNKTEST -D_DEFAULT_SOURCE  -DPDU=S1AP_PDU -DASN_PDU_COLLECTION -I. -o ProtocolIE-Field.o -c ProtocolIE-Field.c
ProtocolIE-Field.c:17649:1: error: redefinition of ‘memb_id_constraint_0’
 memb_id_constraint_0(const asn_TYPE_descriptor_t *td, const void *sptr,
 ^
ProtocolIE-Field.c:17631:1: note: previous definition of ‘memb_id_constraint_0’ was here
 memb_id_constraint_0(const asn_TYPE_descriptor_t *td, const void *sptr,
 ^
ProtocolIE-Field.c:17655:1: error: redefinition of ‘memb_criticality_constraint_0’
 memb_criticality_constraint_0(const asn_TYPE_descriptor_t *td, const void *sptr,
 ^
ProtocolIE-Field.c:17637:1: note: previous definition of ‘memb_criticality_constraint_0’ was here
 memb_criticality_constraint_0(const asn_TYPE_descriptor_t *td, const void *sptr,
 ^
ProtocolIE-Field.c:17661:1: error: redefinition of ‘memb_value_constraint_0’
 memb_value_constraint_0(const asn_TYPE_descriptor_t *td, const void *sptr,_
```____________________________________________________________________________________________
**the details** 
[compile_errors.log](https://github.com/mouse07410/asn1c/files/3058830/compile_errors.log)
________________________________________________________________________________________________
Meanwhile, generating code with cmdline "asn1c -fcompound-names -findirect-choice  -gen-PER -no-gen-example -pdu=all -fno-include-deps ../s1ap-14.4.0.asn", compile errors are the same.

Could you help me ? thank you very very very much.

**Comment by jeick2008** [comment]
@brchiu,  the errors are the same within repo: 
https://github.com/brchiu/asn1c/tree/velichkov_s1ap_plus_option_group

**Comment by velichkov** [comment]
Hi @jeick2008,

Your asn file contains ASN.1 definitions from 36.413 V15.4.0 and the name you've used is a bit misleading - s1ap-14.4.0.asn1.

```asn1
-- 3GPP TS 36.413 V15.4.0 (2018-12)
-- 9.3.5    Common Definitions
-- **************************************************************
--
-- Common definitions
--
-- **************************************************************

S1AP-CommonDataTypes {
itu-t (0) identified-organization (4) etsi (0) mobileDomain (0)  
eps-Access (21) modules (3) s1ap (1) version1 (1) s1ap-CommonDataTypes (3) }
```
Do you need exactly release 15, if not try with [36413-e40.asn](https://raw.githubusercontent.com/nextepc/nextepc/7a8e32f4538407384b073d26b7cb62f6f6506431/lib/s1ap/support/r14.4.0/36413-e40.asn) from the [nextepc](https://github.com/nextepc/nextepc/) project.

I can reproduce the errors you've reported but still can't find whats causing them. We need to find what has been changed in release 15 compared to release 14, try comparing asn modules one by one and summarize the differences.

**Comment by velichkov** [comment]
Hi @jeick2008,

It turns out the order of the ASN.1 modules is important, I've split them in separate files and tried the same order as they are defined in 36.413 and I've compiled it successfully.
```
asn1c -pdu=S1AP-PDU -pdu=all -fcompound-names -findirect-choice -fno-include-deps -flink-skeletons -gen-PER \
	S1AP-PDU-Descriptions.asn \
	S1AP-PDU-Contents.asn  \
	S1AP-IEs.asn \
	S1AP-CommonDataTypes.asn \
	S1AP-Constants.asn \
	S1AP-Containers.asn \
 && make -f converter-example.mk && ./converter-example -h
```
When `S1AP-Containers.asn` is before `S1AP-PDU-Contents.asn` it fails with `error: redefinition of ‘memb_id_constraint_0`, e.g. the following fails.
```
asn1c -pdu=S1AP-PDU -pdu=all -fcompound-names -findirect-choice -fno-include-deps -flink-skeletons -gen-PER \
	S1AP-PDU-Descriptions.asn \
	S1AP-Containers.asn \
	S1AP-PDU-Contents.asn  \
	S1AP-IEs.asn \
	S1AP-CommonDataTypes.asn \
	S1AP-Constants.asn \
 && make -f converter-example.mk && ./converter-example -h
```
And a `SEGFAULT` with the following.
```
asn1c -pdu=S1AP-PDU -pdu=all -fcompound-names -findirect-choice -fno-include-deps -flink-skeletons -gen-PER \
	S1AP-CommonDataTypes.asn \
	S1AP-Constants.asn \
	S1AP-PDU-Descriptions.asn
FATAL: Cannot find external module "S1AP-PDU-Contents" mentioned for "HandoverRequired" at line 258. Obtain this module and instruct compiler to process it too. in S1AP-PDU-Descriptions.asn
Segmentation fault (core dumped)
```

**Comment by jeick2008** [comment]
@velichkov so amazing you are,  thank you very much. I used "cat *.asn > s1ap-14.4.0.asn1" and "asn1c -pdu=..... *.asn", which makes the modules misorder. thank you so much.

**Comment by brchiu** [comment]
@jeick2008 and @velichkov , <del>a common and simple trick is to concatenate all modules into a single file then process it by asn1c, then you don't need to worry about the order of these modules inside this single file.</del>

Sorry I did not read @jeick2008 message that he already concatenate these modules together. My usually approach is save 3gpp spec word file into utf8 text format, then delete all non-ASN1 part and save it to s1ap-xx.y.z.asn1. No problem occurred for this method.
