### ISSUE TITLE
APER segfault

### ISSUE THREAD

**Issue by johvik** [mouse07410/asn1c#56]
When using APER in a CHOICE it segfaults on this line (ct may be NULL):

https://github.com/mouse07410/asn1c/blob/a29f44765cf36a17c398c1b5e71249c793dbdb70/skeletons/constr_CHOICE.c#L1169

For example when encoding ChoiceExtended1 in this asn definition:
```
Enum ::= ENUMERATED { one, two, three, four }

ChoiceExtended1 ::= CHOICE {                                                              
    a Enum,                                                                               
    ...,                                                                                  
    b Enum                                                                                
}
```

**Comment by velichkov** [comment]
Hi @johvik,

Thanks for reporting this problem, could you also provide also `xer` or `aper` files for the example asn1 definition and all commands you need to execute to reproduce this segfault.

Do you have plans to work on a fix?

**Comment by mouse07410** [comment]
Let me second this request. @johvik please provide a `xer` file that demonstrates the problem.

**Comment by johvik** [comment]
Here is a sample that reproduces the issue:

```c
#include <ChoiceExtended1.h>
#include <asn_application.h>

int
main()
{
    ChoiceExtended1_t c;
    memset(&c, 0, sizeof(c));
    c.present = ChoiceExtended1_PR_b;
    c.choice.b = Enum_one;

    uint8_t buffer[500];
    asn_encode_to_buffer(NULL,
                         ATS_ALIGNED_BASIC_PER,
                         &asn_DEF_ChoiceExtended1,
                         &c,
                         &buffer,
                         sizeof(buffer));
}
```
As a temporary workaround I'm using `aper_put_nsnnwn` from https://github.com/vlm/asn1c/pull/125. @velichkov I'm afraid I do not have time to make a permanent fix :/

**Comment by mouse07410** [comment]
@johvik thank you for the code example. But it would really help if you could provide **XER-encoded data file** for the ASN.1 that causes this APER problem.

**Comment by johvik** [comment]
Do you mean this?

```
<ChoiceExtended1>
    <b><one/></b>
</ChoiceExtended1>
```

**Comment by mouse07410** [comment]
**Yes!** Thank you!

**Comment by mouse07410** [comment]
I have a preliminary solution, will push later.

**Comment by mouse07410** [comment]
@johvik thank you - you've provided great info that both unambiguously described the bug, and pointed out a likely solution.
