### ISSUE TITLE
Not able to generate substructure for NGAP.

### ISSUE THREAD

**Issue by vikas-theng** [mouse07410/asn1c#60]
I am using asn1 version asn1c-0.9.29 to generate .c and .h for NGAP protocol. I am able to generate .c and .h but substructure are absent while try to generate with PER . 
Command to run is  $ asn1c file.asn -fcompound-names -gen-PER -pdu=all

**Comment by velichkov** [comment]
Hi @vikas-theng,

> I am using asn1 version asn1c-0.9.29 to generate .c and .h for NGAP protocol. I am able to generate .c and .h but substructure are absent while try to generate with PER .

What exactly do you mean by "substructure are absent"? Can you give some examples?

Read also all messages in #44

**Comment by mouse07410** [comment]
It's been almost a year - so I assume the solution given in #44 resolved this one as well. Otherwise, please speak up, and I'll reopen this issue.
