### ISSUE TITLE
run in assert @libasn1common/asn1_buffer.c:132

### ISSUE THREAD

**Issue by SongShawn** [mouse07410/asn1c#61]
https://github.com/mouse07410/asn1c/blob/vlm_master/libasn1common/asn1_buffer.c:154
The variable actual_length in line 154 overrides the local variable actual_length of the function. So this function always return -1.

**Comment by mouse07410** [comment]
Thank you! I think you're right, and found a bug. Fixed.

**Comment by mouse07410** [comment]
Please re-open if you still have this problem.
