### ISSUE TITLE
Usage of ASN_STRUCT_FREE and filling the 'ie' and freeing it.

### ISSUE THREAD

**Issue by Appuliz** [mouse07410/asn1c#63]
I have a query regarding filling  the structure: 
For example, if I need to fill one ngap structure NG reset, which has a 'cause' and 'reset type' as mandatory fields. So for filling the first 'ie cause', it requires allocating memory and then fills the structure based on procedure id, criticality, and so on.  So before filling the second ie reset type if I'm trying to free the pointer then while executing the program is crashing. Why does this happen? I can free the pointer after filling all the 'ie's', this won't throw any error and encoding works perfectly.
This might be a simple problem but I'm not able to find an appropriate answer. Instead of freeing the ie, can I just use ASN_STRUCT_FREE_CONTENTS _ONLY()? When I tried with ASN_STRUCT_FREE() my program was crashing. But with ASN_STRUCT_FREE_CONTENTS _ONLY() it worked. 

------------------------------------------------------------------
The program crashes if I do in the following way:
```c
NGResetIEs_t *ie;
/**cause */
ie = ( NGResetIEs_t * ) calloc ( 1, sizeof ( NGResetIEs_t )
/** fill the required field like id, criticality etc*/
 ASN_SEQUENCE_ADD ( &ngRset->protocolIEs.list, ie );
free (ie);   
/**reset type */
ie = ( NGResetIEs_t * ) calloc ( 1, sizeof ( NGResetIEs_t )
/** fill the required field like id, criticality etc*/
 ASN_SEQUENCE_ADD ( &ngRset->protocolIEs.list, ie );
free (ie)
asn_encode() //crashes the program
```

-----------------------------------------------------------------
Working code
```c
NGResetIEs_t *ie;
/**cause */
ie = ( NGResetIEs_t * ) calloc ( 1, sizeof ( NGResetIEs_t )
/** fill the required field like id, criticality etc*/
 ASN_SEQUENCE_ADD ( &ngRset->protocolIEs.list, ie );
/**reset type */
ie = ( NGResetIEs_t * ) calloc ( 1, sizeof ( NGResetIEs_t )
/** fill the required field like id, criticality etc*/
 ASN_SEQUENCE_ADD ( &ngRset->protocolIEs.list, ie );
asn_encode() 
free (ie) // works 
```

**Comment by mouse07410** [comment]
Offhand, the structure has "depth" - pointers to other structures that in turn have pointers to other...
Therefore, to reuse it, you should  `ASN_STRUCT_FREE_CONTENTS_ONLY()`, preserving the internal structure of the references to allocated buffers.

In general, things like `free (ie)` would not be good for more complex buffers/structures.

**Comment by mouse07410** [comment]
@Appuliz please let me know if the above helps. 

As there doesn't seem that I could do anything wrt. this issue, I'm closing it. Please feel free to re-open if you'd like to discuss more, or request some actions.
