### ISSUE TITLE
Compile time errors after using -no-gen-* options

### ISSUE THREAD

**Issue by nprobert** [mouse07410/asn1c#69]
Some of the code compiles with errors after generated with -no-gen-BER -no-gen-OER -no-gen-APER options:

ANY_ber.c
ANY_aper.c
BIT_STRING_oer.c
BOOLEAN_ber.c
INTEGER_aper.c
INTEGER_ber.c
INTEGER_oer.c
NativeEnumerated_oer.c
NativeInteger_aper.c
NativeInteger_ber.c
NativeInteger_oer.c
OCTET_STRING_ber.c
OCTET_STRING_oer.c
OPEN_TYPE_ber.c
OPEN_TYPE_oer.c
asn_codecs_prim_ber.c
ber_decoder.c
constr_CHOICE_ber.c
constr_CHOICE_oer.c
constr_SEQUENCE_OF_ber.c
constr_SEQUENCE_aper.c
constr_SEQUENCE_ber.c
constr_SEQUENCE_oer.c
constr_SET_OF_aper.c
constr_SET_OF_ber.c
constr_SET_OF_oer.c
der_encoder.c
oer_encoder.c

Needs #if !defined(ASN_DISABLE_*ER_SUPPORT) / #endif around the code!

**Comment by nprobert** [comment]
Ah, well, I made a fork from your fork, if you'll forkgive me.  Made the changes in my own build and checked it in.

**Comment by eisaev** [comment]
The listed files should not be included in the project when using the specified options. Precompiler conditions were not added specifically for early detection of the use of unnecessary files at the compilation stage.
Please describe exactly how you get this error.

**Comment by nprobert** [comment]
Figured it out.  I was re-generating code on top of old code when I changed the options.
