### ISSUE TITLE
Where is ATS_ALIGNED_BASIC_PER?

### ISSUE THREAD

**Issue by gatopeich** [mouse07410/asn1c#72]
Trying to encode to APER but there is no option for it in `asn_transfer_syntax` enum.

I tried all sort of "-gen-xxx" flags and recompiled `vlm_master` at several points in the history to no avail.

I see a lot of `per_type_encoder_f` instances in headers ending in `..._aper`, and they disappear when compiling with "-no-gen-APER".

Note: Compiling with `-fcompound-names` flag

**Comment by mouse07410** [comment]
First, with the current `vlm_master` you don't need any `-gen-XXX` flags. Now every codec is generated _unless_ a flag is given to **disable** some.

The define you're looking for is in `asn_application.h`

**Comment by gatopeich** [comment]
The issue was with an old `asn_application.h` left under `/usr/local/share/asn1c` by a previous install.
