### ISSUE TITLE
Ignore duplicate definitions from different files (Feature request)

### ISSUE THREAD

**Issue by gatopeich** [mouse07410/asn1c#79]
Hello I am often compiling together different 3GPP specs that include duplicate definitions of the same object.

Here is a very popular one, found in many 3G/4G/5G specs:
```
PLMN-Identity ::= OCTET STRING (SIZE(3))
```
Would it be too hard to allow duplicate definitions when they are exactly the same?

**Comment by mouse07410** [comment]
Sorry, no.

`asn1c` is a very complicated code. AFAICT, what you propose would require a change much more serious than I'm able to handle. Plus, the problem cause here is a broken (incompetent) standard.

A "normal" workaround is removing that definition from all of them into a separate file.
