### ISSUE TITLE
CHOICE_decode_aper: 'value' may be used uninitialized [-Wmaybe-uninitialized]

### ISSUE THREAD

**Issue by pespin** [mouse07410/asn1c#98]
When compiling osmo-cbc.git branch pespin/sbcap, which contains [mouse07410](https://github.com/mouse07410)/[asn1c](https://github.com/mouse07410/asn1c) generated code (asn1c.git current vlm_master, 30219de2d3da888b4f1eea0dd79f2a505000401a).

```
git/osmo-cbc/src/sbcap/gen/constr_CHOICE_aper.c: In function 'CHOICE_decode_aper':
git/osmo-cbc/src/sbcap/gen/constr_CHOICE_aper.c:67:44: warning: 'value' may be used uninitialized [-Wmaybe-uninitialized]
   67 |         value = specs->from_canonical_order[value];
      |                                            ^
git/osmo-cbc/src/sbcap/gen/constr_CHOICE_aper.c:21:9: note: 'value' was declared here
   21 |     int value;
      |         ^~~~~
```

```
 $ gcc --version
gcc (GCC) 12.1.0

```

**Comment by pespin** [comment]
Not sure what's the proper fix here. Looks like "value" is indeed being used initialized at least if "ct == NULL", and maybe also in other cases where ct != NULL.

**Comment by mouse07410** [comment]
I think this is simple to take care of, so pushing the fix.

**Comment by pespin** [comment]
A regression was introduced with your commit, fix available here:
https://github.com/mouse07410/asn1c/pull/104/commits/7e1371ab5016adfa1d3199eec9307246f7a85942
